robots:
  niryo:
    workspaces:
      - id: "niryo_ws"
        observation_pose:
          x: 0.173
          y: -0.002
          z: 0.40
          roll: 0.0
          pitch: 1.57
          yaw: 0.0
        image_shape: [640, 480, 3]
    simulation_workspaces:
      - id: "gazebo_1"
        observation_pose:
          x: 0.173
          y: -0.002
          z: 0.40
          roll: 0.0
          pitch: 1.57
          yaw: 0.0
        image_shape: [640, 480, 3]
