robots:
  widowx:
    workspaces:
      - id: "widowx_ws"
        observation_pose:
          x: 0.25
          y: 0.0
          z: 0.30
          roll: 0.0
          pitch: 1.57
          yaw: 0.0
        image_shape: [640, 480, 3]
    simulation_workspaces:
      - id: "gazebo_widowx_1"
        observation_pose:
          x: 0.25
          y: 0.0
          z: 0.30
          roll: 0.0
          pitch: 1.57
          yaw: 0.0
        image_shape: [640, 480, 3]
